[0_RootFS] Add LLVMBootstrap v13 (#4748)
* [0_RootFS] Add LLVMBootstrap v13

* [0_RootFS] Fix patch to build llvm on Musl

Revert change that was removing the inclusion of `sys/sysinfo.h`: it was causing
`sysinfo` to not be defined correctly:

```
/workspace/srcdir/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:221:32: error: invalid application of 'sizeof' to incomplete type '__sanitizer::sysinfo'
  221 |   unsigned struct_sysinfo_sz = sizeof(struct sysinfo);
      |                                ^~~~~~~~~~~~~~~~~~~~~~
```

* [0_RootFS] Compile LLVMBootstrap with `-Wl,-rpath-link,${prefix}/${target}/lib64`

* [0_RootFS] Also set `LD_LIBRARY_PATH` when building LLVMBootstrap