add GDAL builder (#293)
* add GDAL build script

* add CompilerSupportLibraries dependency

This gets us past a failure during the `configure` step where it checks the PROJ dependency by compiling test programs. This led to this failure related to `libstdc++`:

```
configure:24103: checking for proj_create_from_wkt in -lproj
configure:24128: c++ -std=c++11 -o conftest -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2   conftest.cpp -lproj  -L/workspace/destdir/lib -lproj -lz -L/workspace/destdir -L/workspace/destdir/lib -lpthread -lm -lrt -ldl  >&5
/workspace/destdir/lib/libproj.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
/workspace/destdir/lib/libproj.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>
```

* add review suggestions

* add missing -L flag in LDFLAGS

Co-Authored-By: Mosè Giordano <giordano@users.noreply.github.com>

* Clear out `.la` files

* [GDAL] Customise name of PROJ lib to link against

* [GDAL] Fixes for Windows and PowerPC

* [GDAL] use latest bugfix release 3.0.3

Includes a few build bug fixes:
https://github.com/OSGeo/gdal/blob/v3.0.3/gdal/NEWS

* [GDAL] Build with GCC v6, for compatibility with GEOS

Co-authored-by: Mosè Giordano <giordano@users.noreply.github.com>