[normaliz] rebuild to fix MPFR version, because FLINT needs MPFR (#1942)
to make those poor macos users happy again:
ERROR: LoadError: LoadError: InitError: could not load library /Users/runner/.julia/artifacts/34750e7597595ecce93a0a04cd79cbb7514e475f/lib/libnormaliz.3.dylib
dlopen(/Users/runner/.julia/artifacts/34750e7597595ecce93a0a04cd79cbb7514e475f/lib/libnormaliz.3.dylib, 1): Library not loaded: @rpath/libmpfr.6.dylib
  Referenced from: /Users/runner/.julia/artifacts/34750e7597595ecce93a0a04cd79cbb7514e475f/lib/libnormaliz.3.dylib
  Reason: Incompatible library version: libnormaliz.3.dylib requires version 8.0.0 or later, but libmpfr.dylib provides version 7.0.0