[PROJ] update to 8.2 (#4097)
* [PROJ] update to 8.2

* add missing comma

Co-authored-by: Mosè Giordano <giordano@users.noreply.github.com>

* Try to debug

* Revert "Try to debug"

This reverts commit 0ee260f1a003f11e224cd6839fe0d181105f4c6c.

* add -lcurl on x86_64-linux-musl

It is not understood why this is a problem, only for this platform. Without this the error is:

```
[21:29:23] cd /workspace/srcdir/proj-8.2.0/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/binproj.dir/link.txt --verbose=true
[21:29:23] /opt/bin/x86_64-linux-musl-libgfortran3-cxx03/x86_64-linux-musl-g++ --sysroot=/opt/x86_64-linux-musl/x86_64-linux-musl/sys-root/  -O3 -DNDEBUG   CMakeFiles/binproj.dir/apps/proj.cpp.o CMakeFiles/binproj.dir/apps/emess.cpp.o CMakeFiles/binproj.dir/apps/utils.cpp.o  -o ../bin/proj   -L/workspace/srcdir/proj-8.2.0/build/lib  -Wl,-rpath,/workspace/srcdir/proj-8.2.0/build/lib: ../lib/libproj.so.22.2.0
[21:29:23] ../lib/libproj.so.22.2.0: undefined reference to `curl_easy_perform@CURL_4'
[21:29:23] ../lib/libproj.so.22.2.0: undefined reference to `curl_easy_init@CURL_4'
[21:29:23] ../lib/libproj.so.22.2.0: undefined reference to `curl_easy_getinfo@CURL_4'
[21:29:23] ../lib/libproj.so.22.2.0: undefined reference to `curl_easy_setopt@CURL_4'
[21:29:23] ../lib/libproj.so.22.2.0: undefined reference to `curl_easy_cleanup@CURL_4'
[21:29:23] collect2: error: ld returned 1 exit status
[21:29:23] make[2]: *** [src/CMakeFiles/binproj.dir/build.make:135: bin/proj] Error 1
[21:29:23] make[1]: *** [CMakeFiles/Makefile2:404: src/CMakeFiles/binproj.dir/all] Error 2
```

Co-authored-by: Mosè Giordano <giordano@users.noreply.github.com>