[PROJ] update to 9.2.1, build with libtiff 4.5 (#6930)
* [PROJ] update to 9.2.1, fix libtiff breakage

* attempt to fix musl curl linking

```
/opt/bin/x86_64-linux-musl-libgfortran3-cxx03/x86_64-linux-musl-gcc --sysroot=/opt/x86_64-linux-musl/x86_64-linux-musl/sys-root/ -lcurl  CMakeFiles/cmTC_7bab4.dir/testCCompiler.c.o -o cmTC_7bab4
/opt/x86_64-linux-musl/x86_64-linux-musl/sys-root//usr/local/lib/libcurl.so: undefined reference to `nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation'
```

* loosen libtiff, add compat for libcurl

* 4.5.1 compat

* Delete system libcurl on x86_64 musl