Fix libjulia_jll building regression (#2317)
Without this, we are now seeing the following:

     ---> apk add coreutils libuv-dev utf8proc
    ERROR: unsatisfiable constraints:
      ninja (virtual):
        provided by: samurai
        required by: world[ninja]
     ---> apk add coreutils libuv-dev utf8proc
    Previous command exited with 1
    Child Process exited, exit code 1

[skip ci]