Wizard recipe: MAiNGO-v0.7.2 (#7812)
* New Recipe: MAiNGO v0.7.2

* Delete unused patch and cleanup build_tarballs.jl.

Add comments explaining why certain platforms are not yet build.
Add expansion over cxxstring and libgfortran 4 and 5.

* Lower preferred_gcc_version to 9

* Apply suggestions from code review

Apply directly useable suggestions.

Co-authored-by: Mosè Giordano <giordano@users.noreply.github.com>

* Update M/MAiNGO/build_tarballs.jl

Add suggested commands for moving lib and bin targets.

Co-authored-by: Mosè Giordano <giordano@users.noreply.github.com>

* Try building for MacOS and FreeBSD

* Filter out non-working platforms instead of picking ones that work

* Fix CMake options

* Fix missing build folder in first CMake command

* Fix missing build folder in first CMake command (again)

* Fix typo in CMAKE_TARGET_TOOLCHAIN

* Remove FreeBSD build.

Not supported upstream and fails on trial build with

/workspace/srcdir/maingo/build/dep/ipopt/IpoptConfig/include/config.h:17:4: error: #error "No finite/_finite function available"
[16:31:28]    17 |   #error "No finite/_finite function available"

Likely would need deeper investigation and modification of the CMake files, as Ipopt without CMake seems to build.

* Fix bash script error

* Test Clang for MacOS

* Try forcing SDK 10.15 for std::variant

* Fix where if statement ends

* Revert to using GCC for MacOS

---------

Co-authored-by: Aron Zingler <aron.zingler@rwth-aachen.de>
Co-authored-by: Mosè Giordano <giordano@users.noreply.github.com>