Revert "Add postgres support"
It seems to find the wrong postgres:

```
[07:34:13] In file included from /workspace/srcdir/gdal-3.5.1/ogr/ogrsf_frmts/pg/ogr_pg.h:35,
[07:34:13]                  from /workspace/srcdir/gdal-3.5.1/ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp:31:
[07:34:13] /opt/aarch64-linux-gnu/aarch64-linux-gnu/sys-root/usr/local/include/libpq-fe.h:29:10: fatal error: postgres_ext.h: No such file or directory
[07:34:13]  #include "postgres_ext.h"
[07:34:13]           ^~~~~~~~~~~~~~~~
```

This reverts commit da9909dc7466078d8553d9798d0538a1d54849f0.