[oneTBB] bump version and try adding mingw platforms back in (#4263)
* [oneTBB] bump version and try adding mingw platforms back in

* wrap musl patch in a target branch to at least be able to look at CI, still need to refactor to current master

* switch back to tagged release source, extract some of the changes from upstream into patches for mingw

* add wildcard to srcdir that I forgot

* [oneTBB] Require Windows Vista

* [oneTBB] Add alternative name for libtbb on Windows

* [oneTBB] Use GCC 5

x86_64-w64-mingw32 was failing with

```
/workspace/srcdir/oneTBB-2021.5.0/src/tbb/tools_api/ittnotify_static.c:291:1: error: missing initializer for member ‘_RTL_CRITICAL_SECTION::DebugInfo’ [-Werror=missing-field-initializers]
```

* [oneTBB] Disable LTO with Clang

* add platform filter to remove i686 mingw

Co-authored-by: Mosè Giordano <mose@gnu.org>