Adding ROOT_jll (#9300)
* Merge branch 'ROOT-1'

* Added more library products

* Build the global PCH

* typo in patch

* Temporary fix for host local prefix to simplify recipe

* First working version.

Cross-compiling related issues with root-cling fixed for linux with glibc. MacOS not yet supported.

* Fix an issue when compilation is done the on buildkite CI

* Update R/ROOT/build_tarballs.jl

Co-authored-by: Mosè Giordano <765740+giordano@users.noreply.github.com>

* use lock_microarchitecture=false option instead of patching compiler script

skip-checks: true

* fixed compilation issue with lastly committed oneTBB_jll by setting compat flag to previous version

Compilation error was:

```
from /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/9.1.0/stdexcept:39,
from /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/9.1.0/array:39,
from /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/9.1.0/tuple:39,
from /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/9.1.0/functional:54,
from /workspace/srcdir/root/core/foundation/inc/TError.h:37,
from /workspace/srcdir/root/core/cont/inc/ROOT/TSeq.hxx:15,
from /workspace/srcdir/root/core/base/inc/ROOT/TExecutorCRTP.hxx:15,
from /workspace/srcdir/root/core/imt/inc/ROOT/TThreadExecutor.hxx:25,
from /workspace/srcdir/root/core/imt/src/TThreadExecutor.cxx:4:
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/bits/waitstatus.h:66:7: note: candidate: ‘wait::wait()’
     66 | union wait
        |       ^~~~                                                                                                                                               /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/bits/waitstatus.h:66:7: note:   candidate expects 0 arguments, 2 provided
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/bits/waitstatus.h:66:7: note: candidate: ‘constexpr wait::wait(const wait&)’                         /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/bits/waitstatus.h:66:7: note:   candidate expects 1 argument, 2 provided                             /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/bits/waitstatus.h:66:7: note: candidate: ‘constexpr wait::wait(wait&&)’
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/bits/waitstatus.h:66:7: note:   candidate expects 1 argument, 2 provided
```

* change `nproc` by $nproc and reduced number of parallel jobs.

Beware $nproc ignores the cpu affinity mask (used by slurm batch system to share cpus of a node).

Co-authored-by: Mosè Giordano <765740+giordano@users.noreply.github.com>

* Dependencies reviewed

- add uuid to dependencies that were missing it;
- remove LAPACK_jll, OpenBLAS_jll;
- use libblastrampoline for the BLAS dependency;
- add missing dependencies, GLU_jll, GLEW_jll, nlohmann_json_jll, and CFITSIO_jll.

Co-authored-by: Mosè Giordano

* Add diagnostic on kill and remove LLVM link jobs limits

Previous buildkite CI timed out with message "Received cancellation signal, interrupting." With this commit we attempt to trap kill signal and display stats on running processes before exiting.

Measurements done to debug the issue show a lower LLVM link command memory footprint than anticipated. Removed the limit on number of LLVM link jobs,

* Remove signal trap and change linker

Signal trap did not work. Mosè suggested to try with ldd linker.

* add util_linux_jll dependencies

ldd error has indicated that libuuid is missing.

* rollback previous commit and switched off Davix

Adding util_linux_jll did not solve missing uuid_gen symbol error.
Remove it and switch off Davix build.

* Trying Unix Makefile to solve CI build issue

* Revert to ninja and try CCACHE_RECACHE

* export CCACHE_RECACHE

* Attempt CI with less output lines

* Second build with a single job for debugging

* Roll back to version before the CI issue in view of introducing changes piece by piece

* remove LAPACK and OpenBLAS _jll dependencies

* add GLU_jll dependency

* add GLEW_jll dependency

* add nlohmann_json_jll dependency

* Revert "add nlohmann_json_jll dependency"

This reverts commit 3c906f2c6236bf19633463e97fd5cc0bc4ac085e.

* add CFITSIO_jll dependency

* add uuid of dependencies that missed it

* fix blas depedency using OpenBLAS32 since ROOT uses the PL64 interface

---------

Co-authored-by: Philippe Gras <philippe.gras@cern.ch>
Co-authored-by: Mosè Giordano <765740+giordano@users.noreply.github.com>