[msolve] rebuild with old MPFR
... to restore compatibility with Julia 1.6 on macOS. Before this, we
got this error on an Intel Mac:

    ERROR: LoadError: LoadError: InitError: could not load library "JULIADEPOT/artifacts/0ee20e199c8939d53a5262356e455ebed54860a1/lib/libmsolve.dylib"
    dlopen(JULIADEPOT/artifacts/0ee20e199c8939d53a5262356e455ebed54860a1/lib/libmsolve.dylib, 1): Library not loaded: @rpath/libmpfr.6.dylib
     Referenced from: JULIADEPOT/artifacts/0ee20e199c8939d53a5262356e455ebed54860a1/lib/libmsolve-0.4.8.dylib
     Reason: Incompatible library version: libmsolve.dylib requires version 9.0.0 or later, but libmpfr.dylib provides version 8.0.0