[libgeotiff] build 1.7.0
Needed to progress with #4193, since both have a PROJ dependency.

Had to add LibCURL_jll as a direct dependency (rather than through PROJ), to avoid this issue:

```
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root//usr/local/lib/libcurl.so.4: undefined reference to `mbedtls_net_recv'
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib/libproj.so.22.2.0: undefined reference to `curl_easy_perform@CURL_4'
```